### PR TITLE
Lib scrape fixes

### LINKED ISSUE #689: winmdgenerator: x86, arm64 libs are not scanned correctly resulting in missing metadata
MetadataTasks scans import lib dumpbin output for function names. It's currently pulling out `Symbol name`, which may be decorated, depending on target platform (e.g. _Function@0 on x86, Function on x64, etc.). This should instead read the undecorated `Name` field.

https://github.com/microsoft/win32metadata/blob/832ff5798733fc292c3bdbc73c8ae81e7a0cda4b/sources/GeneratorSdk/MetadataTasks/ScanLibs.cs#L35

### PR DESCRIPTION
**Pull request by sotteson1**
* Fixes #689 - Fixes lib scraping issues
* Add tests around new lib scraping code
* Refactor how tests are called in DoAll.bat

These changes will make it easier to move to a new WinSDK, which I hope to do soon.

### CODE REVIEW

File: sources/MetadataUtils/LibScraper.cs [hunk 1]
```diff
@@ -0,0 +1,266 @@
...
+                if (importHeader.ImportType != ImportType.Code)
+                {
+                    continue;
+                }
+
+                string symbolName = ReadNullTermString(libReader);
+                string dllName = ReadNullTermString(libReader);
+                string procName = symbolName;
+
+                // If it's x86, try to undecorate it
```
Comment (riverar) [inline sources/MetadataUtils/LibScraper.cs:110]: @sotteson1 What about x64/arm64ec though?
